import { useState, useEffect } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { cn } from '@/lib/utils'
import { supabase, isSupabaseConfigured } from '@/lib/supabase'

const leadFormSchema = z.object({
  name: z.string().min(1, 'Name is required').min(2, 'Name must be at least 2 characters'),
  email: z.string().min(1, 'Email is required').email('Please enter a valid email address'),
  phone: z.string().optional(),
  source: z
    .string()
    .min(1, 'Please select a source')
    .refine((val) => ['Google', 'Referral', 'Other'].includes(val), {
      message: 'Please select a valid source',
    }),
  interest: z.string().min(1, 'Interest is required'),
  note: z.string().min(1, 'Note is required'),
})

type LeadFormData = z.infer<typeof leadFormSchema>

interface LeadFormProps {
  onSubmit?: (data: LeadFormData) => void | Promise<void>
  className?: string
}

const LeadForm = ({ onSubmit, className }: LeadFormProps) => {
  const [showSuccess, setShowSuccess] = useState(false)

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
    reset,
  } = useForm<LeadFormData>({
    resolver: zodResolver(leadFormSchema),
    defaultValues: {
      name: '',
      email: '',
      phone: '',
      source: undefined,
      interest: '',
      note: '',
    },
  })

  useEffect(() => {
    if (showSuccess) {
      const timer = setTimeout(() => {
        setShowSuccess(false)
      }, 3000) // Hide after 3 seconds

      return () => clearTimeout(timer)
    }
  }, [showSuccess])

  const onFormSubmit = async (data: LeadFormData) => {
    try {
      // Check if Supabase is configured
      if (!isSupabaseConfigured) {
        console.warn('Supabase is not configured. Form data:', data)
        // Still call the custom handler and show success for development
        await onSubmit?.(data)
        reset()
        setShowSuccess(true)
        alert('⚠️ Supabase is not configured. Please set up your .env file with Supabase credentials.\n\nForm data logged to console.')
        return
      }

      // Insert into Supabase
      // Note: id and created_at are auto-generated by the database
      const { error: supabaseError } = await supabase
        .from('leads')
        .insert([
          {
            name: data.name,
            email: data.email,
            phone: data.phone || null,
            source: data.source,
            interest: data.interest,
            note: data.note,
            assigned_to: null, // Optional field, can be assigned later
          },
        ])

      if (supabaseError) {
        throw supabaseError
      }

      // Call custom onSubmit handler if provided
      await onSubmit?.(data)
      
      // Reset form and show success
      reset()
      setShowSuccess(true)
    } catch (error) {
      console.error('Error submitting form:', error)
      alert(`Failed to submit form: ${error instanceof Error ? error.message : 'Unknown error'}`)
    }
  }

  return (
    <div className={cn('w-full max-w-2xl mx-auto', className)}>
      {/* Success Message */}
      <div
        className={cn(
          'fixed top-4 left-1/2 transform -translate-x-1/2 z-50',
          'bg-green-500 text-white px-6 py-4 rounded-lg shadow-lg',
          'flex items-center gap-3 min-w-[300px] max-w-md',
          'transition-all duration-300 ease-in-out',
          showSuccess
            ? 'opacity-100 translate-y-0 scale-100'
            : 'opacity-0 -translate-y-4 scale-95 pointer-events-none'
        )}
      >
        <svg
          className="w-6 h-6 flex-shrink-0"
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M5 13l4 4L19 7"
          />
        </svg>
        <div>
          <p className="font-semibold">Successfully Submitted!</p>
          <p className="text-sm text-green-100">
            Thank you for your interest. We'll get back to you soon.
          </p>
        </div>
      </div>

      <form
        onSubmit={handleSubmit(onFormSubmit)}
        className="bg-card border border-border rounded-lg p-6 shadow-sm space-y-6"
      >
        <div>
          <h2 className="text-2xl font-bold text-foreground mb-2">
            Get in Touch
          </h2>
          <p className="text-muted-foreground">
            Fill out the form below and we'll get back to you soon.
          </p>
        </div>

        {/* Name Field */}
        <div>
          <label
            htmlFor="name"
            className="block text-sm font-medium text-foreground mb-2"
          >
            Name <span className="text-destructive">*</span>
          </label>
          <input
            id="name"
            type="text"
            {...register('name')}
            className={cn(
              'w-full px-4 py-2 border rounded-md bg-background text-foreground',
              'focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2',
              'transition-colors',
              errors.name
                ? 'border-destructive focus:ring-destructive'
                : 'border-input'
            )}
            placeholder="Enter your full name"
          />
          {errors.name && (
            <p className="mt-1 text-sm text-destructive">{errors.name.message}</p>
          )}
        </div>

        {/* Email Field */}
        <div>
          <label
            htmlFor="email"
            className="block text-sm font-medium text-foreground mb-2"
          >
            Email <span className="text-destructive">*</span>
          </label>
          <input
            id="email"
            type="email"
            {...register('email')}
            className={cn(
              'w-full px-4 py-2 border rounded-md bg-background text-foreground',
              'focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2',
              'transition-colors',
              errors.email
                ? 'border-destructive focus:ring-destructive'
                : 'border-input'
            )}
            placeholder="Enter your email address"
          />
          {errors.email && (
            <p className="mt-1 text-sm text-destructive">{errors.email.message}</p>
          )}
        </div>

        {/* Phone Field */}
        <div>
          <label
            htmlFor="phone"
            className="block text-sm font-medium text-foreground mb-2"
          >
            Phone
          </label>
          <input
            id="phone"
            type="tel"
            {...register('phone')}
            className={cn(
              'w-full px-4 py-2 border rounded-md bg-background text-foreground',
              'focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2',
              'transition-colors',
              errors.phone
                ? 'border-destructive focus:ring-destructive'
                : 'border-input'
            )}
            placeholder="Enter your phone number (optional)"
          />
          {errors.phone && (
            <p className="mt-1 text-sm text-destructive">{errors.phone.message}</p>
          )}
        </div>

        {/* Source Field */}
        <div>
          <label
            htmlFor="source"
            className="block text-sm font-medium text-foreground mb-2"
          >
            How did you hear about us? <span className="text-destructive">*</span>
          </label>
          <select
            id="source"
            {...register('source')}
            className={cn(
              'w-full px-4 py-2 border rounded-md bg-background text-foreground',
              'focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2',
              'transition-colors',
              errors.source
                ? 'border-destructive focus:ring-destructive'
                : 'border-input'
            )}
          >
            <option value="">Select a source</option>
            <option value="Google">Google</option>
            <option value="Referral">Referral</option>
            <option value="Other">Other</option>
          </select>
          {errors.source && (
            <p className="mt-1 text-sm text-destructive">{errors.source.message}</p>
          )}
        </div>

        {/* Interest Field */}
        <div>
          <label
            htmlFor="interest"
            className="block text-sm font-medium text-foreground mb-2"
          >
            What are you interested in? <span className="text-destructive">*</span>
          </label>
          <textarea
            id="interest"
            {...register('interest')}
            rows={4}
            className={cn(
              'w-full px-4 py-2 border rounded-md bg-background text-foreground',
              'focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2',
              'transition-colors resize-none',
              errors.interest
                ? 'border-destructive focus:ring-destructive'
                : 'border-input'
            )}
            placeholder="Tell us what you're interested in... (required)"
          />
          {errors.interest && (
            <p className="mt-1 text-sm text-destructive">{errors.interest.message}</p>
          )}
        </div>

        {/* Note Field */}
        <div>
          <label
            htmlFor="note"
            className="block text-sm font-medium text-foreground mb-2"
          >
            Additional Notes <span className="text-destructive">*</span>
          </label>
          <textarea
            id="note"
            {...register('note')}
            rows={4}
            className={cn(
              'w-full px-4 py-2 border rounded-md bg-background text-foreground',
              'focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2',
              'transition-colors resize-none',
              errors.note
                ? 'border-destructive focus:ring-destructive'
                : 'border-input'
            )}
            placeholder="Any additional information you'd like to share... (required)"
          />
          {errors.note && (
            <p className="mt-1 text-sm text-destructive">{errors.note.message}</p>
          )}
        </div>

        {/* Submit Button */}
        <div className="flex gap-4">
          <button
            type="submit"
            disabled={isSubmitting}
            className={cn(
              'flex-1 px-6 py-3 rounded-md font-medium transition-colors',
              'bg-primary text-primary-foreground hover:bg-primary/90',
              'disabled:opacity-50 disabled:cursor-not-allowed',
              'focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2'
            )}
          >
            {isSubmitting ? 'Submitting...' : 'Submit'}
          </button>
          <button
            type="button"
            onClick={() => reset()}
            disabled={isSubmitting}
            className={cn(
              'px-6 py-3 rounded-md font-medium transition-colors',
              'bg-secondary text-secondary-foreground hover:bg-secondary/80',
              'disabled:opacity-50 disabled:cursor-not-allowed',
              'focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2'
            )}
          >
            Reset
          </button>
        </div>
      </form>
    </div>
  )
}

export default LeadForm
